version: '3'

services:

  redis:
    image: redis:rc-alpine3.11
    container_name: redis
    expose:
      - '6379'
    networks:
      - backend

  esb:
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    container_name: node
    ports:
      - 80:2013
    networks:
      - backend

networks:
  backend:
    driver: bridge