on:
  push:
    branches:
      - master

name: ESB_Container_NodeJS_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Build and push image'
    - uses: azure/docker-login@v1
      with:
        login-server: daniimor.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t daniimor.azurecr.io/esb:${{ github.sha }}
        docker push daniimor.azurecr.io/esb:${{ github.sha }} 
      
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: daniimor.azurecr.io/esb:${{ github.sha }}
        registry-login-server: daniimor.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: esb
        location: 'west us'

    - name: Azure logout
      run: |
        az logout